# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#what branch we are watching
trigger:
  - 'master'

pool: 
  vmImage: 'vs2017-win2016'

#watch for PR's
pr: 'none'

#groups sequential actions
steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: my-sonarcloud-connection
    organization: my-organization-name
    projectKey: my-project-name

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: 'Projects/p0/p0/*.sln'

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: 'Projects\p0\p0_test\bin\Debug\netcoreapp3.1\p0_test.dll'
    resultsFolder: 'D:\a\1\TestResults'
    codeCoverageEnabled: true
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'
